package view;
import java.awt.Button;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Jogador;
import model.JogoVelha;
import model.Tabuleiro;
import javax.swing.JButton;
// a interação esta dentro da interface, entao inicia-se aqui
public class JogoVelhaGUI extends javax.swing.JFrame{
    Jogador jogador1 = new Jogador('X');
    Jogador jogador2 = new Jogador('0');
    JogoVelha jogoVelha = new JogoVelha(jogador1,jogador2);       
    /** Creates new form JogoVelhaGUI */
    public JogoVelhaGUI(){
        initComponents();
        setSize(700,500);          
    }    
    public void limparTela(){
    // limpa a tela
        for (int count=0;count < pnJogadas.getComponentCount(); count++){
            if (pnJogadas.getComponent(count) instanceof JButton){
                JButton botao = (JButton)(pnJogadas.getComponent(count));
                botao.setText(" ");
            }
        }
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnGrupo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroDevitoriaDoJogador1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumerosDeVitoriasDoJogador2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        NumeroDeEmpates = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbJogo = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        pnJogadas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btMatriz = new javax.swing.JButton();
        btMatrizInversa = new javax.swing.JButton();
        btMatrizTransposta = new javax.swing.JButton();
        btSomaMatriz = new javax.swing.JButton();
        btSubMatriz = new javax.swing.JButton();
        btMultiMatriz = new javax.swing.JButton();
        btBinario = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnJogo = new javax.swing.JMenu();
        jmnIniciar = new javax.swing.JMenuItem();
        jmnTipo = new javax.swing.JMenu();
        jmnPP = new javax.swing.JRadioButtonMenuItem();
        jmnPC = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jmnSair = new javax.swing.JMenuItem();
        jmnRanking = new javax.swing.JMenu();
        jmnMostrarRanking = new javax.swing.JMenuItem();
        jmnZerarRanking = new javax.swing.JMenuItem();
        jmnSobre = new javax.swing.JMenu();
        jmnJogoVelha = new javax.swing.JMenuItem();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do jogo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setText("Jogador 1            Simbolo: X");

        NumeroDevitoriaDoJogador1.setText("Números de vitorias:0");

        jLabel3.setText("Jogador 2           Simbolo: O");

        NumerosDeVitoriasDoJogador2.setText("Números de vitorias:0");

        NumeroDeEmpates.setText("Números de empate:0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NumeroDevitoriaDoJogador1)
                            .addComponent(jLabel3)
                            .addComponent(NumerosDeVitoriasDoJogador2))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NumeroDeEmpates)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumeroDevitoriaDoJogador1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumerosDeVitoriasDoJogador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroDeEmpates)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");

        lbJogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbJogo.setForeground(new java.awt.Color(0, 51, 204));
        lbJogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJogo.setText("ADS da Velha");

        pnBotoes.setLayout(new java.awt.GridLayout(1, 0));

        pnJogadas.setLayout(new java.awt.GridLayout(3, 3));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setName("00"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setName("01"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setName("02"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setName("10"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setName("11"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setName("12"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setName("20"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setName("21"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setName("22"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar(evt);
            }
        });
        pnJogadas.add(jButton9);

        btMatriz.setText("Matriz");
        btMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatrizActionPerformed(evt);
            }
        });

        btMatrizInversa.setText("Matriz Inversa");
        btMatrizInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatrizInversaActionPerformed(evt);
            }
        });

        btMatrizTransposta.setText("Matriz Transposta");
        btMatrizTransposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatrizTranspostaActionPerformed(evt);
            }
        });

        btSomaMatriz.setText("Soma De Matriz");

        btSubMatriz.setText("Subtração De Matriz");

        btMultiMatriz.setText("Multiplicação de Matriz");

        btBinario.setText("Binario");

        jButton10.setText("Octal");

        btIniciar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIniciar.setText("Iniciar Jogo");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJogo(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setText("Sair do Jogo");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });

        jButton11.setText("Hexadecimal");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jmnJogo.setText("Jogo");

        jmnIniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmnIniciar.setText("Iniciar");
        jmnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJogo(evt);
            }
        });
        jmnJogo.add(jmnIniciar);

        jmnTipo.setText("Tipo de jogo");

        mnGrupo.add(jmnPP);
        jmnPP.setSelected(true);
        jmnPP.setText("Pessoa vs Pessoa");
        jmnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaClick(evt);
            }
        });
        jmnTipo.add(jmnPP);

        mnGrupo.add(jmnPC);
        jmnPC.setText("Pessoa vs Computador");
        jmnPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computadorClick(evt);
            }
        });
        jmnTipo.add(jmnPC);

        jmnJogo.add(jmnTipo);
        jmnJogo.add(jSeparator1);

        jmnSair.setText("Sair");
        jmnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        jmnJogo.add(jmnSair);

        jMenuBar1.add(jmnJogo);

        jmnRanking.setText("Ranking");

        jmnMostrarRanking.setText("Mostrar Ranking");
        jmnMostrarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRanking(evt);
            }
        });
        jmnRanking.add(jmnMostrarRanking);

        jmnZerarRanking.setText("Zerar Ranking");
        jmnZerarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerarRanking(evt);
            }
        });
        jmnRanking.add(jmnZerarRanking);

        jMenuBar1.add(jmnRanking);

        jmnSobre.setText("Sobre");

        jmnJogoVelha.setText("ADS da Velha");
        jmnJogoVelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAbout(evt);
            }
        });
        jmnSobre.add(jmnJogoVelha);

        jMenuBar1.add(jmnSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btSubMatriz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btMatrizTransposta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btMatriz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btMatrizInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btSomaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                    .addComponent(btMultiMatriz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbJogo)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMatrizInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btSubMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMultiMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btSomaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btMatrizTransposta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(pnJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciar)
                    .addComponent(btSair))
                .addGap(23, 23, 23)
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaClick
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Se você confirmar estará encerrando o Jogo Atual e recomeçando um novo jogo\n Tem certeza que deseja prosseguir?") == 0){
            jogoVelha.iniciar(false);            
            // limpa a tela
            this.limparTela();           
        }
        else{
            mnGrupo.setSelected(jmnPC.getModel(),true);
        }
    }//GEN-LAST:event_pessoaClick

    private void computadorClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computadorClick
        // TODO add your handling code here:       
        if (JOptionPane.showConfirmDialog(null,"Se você confirmar estará encerrando o Jogo Atual e recomeçando um novo jogo\n Tem certeza que deseja prosseguir?") == 0){
            jogoVelha.iniciar(true);
            // limpa a tela
            this.limparTela();
        }
        else{
            mnGrupo.setSelected(jmnPP.getModel(),true);
        }
    }//GEN-LAST:event_computadorClick
    
    private void mostrarRanking(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRanking
        String rank;
        rank = "Vitorias do Jogador 1:  "+jogador1.getVitorias()+"\n"+
                "Vitorias do Jogador 2:  "+jogador2.getVitorias()+"\n"+
                "Empates :  "+jogoVelha.getContaEmpates();
        JOptionPane.showMessageDialog(null,rank, "Ranking", 1);
    }//GEN-LAST:event_mostrarRanking

    private void zerarRanking(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerarRanking
        jogador1.zerarVitorias();
        jogador2.zerarVitorias();
       // jogoVelha.zeraEmpates();
    }//GEN-LAST:event_zerarRanking
    
    private void showAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAbout
        
        String sobre = "Jogo da Velha\nAlunos:  Arthur Dias Mesquita\n                Douglas Barbosa Vieira\n";
        JOptionPane.showMessageDialog(null,sobre);
    }//GEN-LAST:event_showAbout
    
    private void iniciarJogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJogo
        jogoVelha.iniciar(this.jogoVelha.isSncpu());
        this.limparTela();
    }//GEN-LAST:event_iniciarJogo
    
    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        System.exit(0);
    }//GEN-LAST:event_sair

    private void jogar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogar

        if (!this.jogoVelha.isFimDoJogo()){
            JButton botao = (JButton) evt.getSource();
            int linha = Integer.parseInt(botao.getName().substring(0,1));
            int coluna = Integer.parseInt(botao.getName().substring(1,2));

            executaJogada(botao, linha, coluna);


            String cmp = jogoVelha.performJogada();
            if (cmp != null){
                botao = jogadaComputador(cmp);
                if (botao != null){
                    linha = Integer.parseInt(botao.getName().substring(0,1));
                    coluna = Integer.parseInt(botao.getName().substring(1,2));
                    executaJogada(botao, linha, coluna);
                }
            }
        } 
        else{
            JOptionPane.showMessageDialog(null,"Jogo encerrado", "Aviso", 2);
            
        }
        
    }//GEN-LAST:event_jogar

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void btMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMatrizActionPerformed

    private void btMatrizInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatrizInversaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMatrizInversaActionPerformed

    private void btMatrizTranspostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatrizTranspostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMatrizTranspostaActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed
   
    public void executaJogada(JButton botao, int linha, int coluna) {       
        Tabuleiro tabuleiro = this.jogoVelha.getTabuleiro();
        if (tabuleiro.estaLivre(linha, coluna)){
            char simbolo = jogoVelha.fazerJogada(linha, coluna);
            botao.setText(String.valueOf(simbolo));
            if (jogoVelha.isFimDoJogo()){
                if (jogoVelha.getVencedor() != null){
                    if (jogoVelha.getVencedor() == jogoVelha.getJogador1()){
                        JOptionPane.showMessageDialog(null,"O Jogador 1 foi o vencedor");
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"O Jogador 2 foi o vencedor");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Houve empate");
                }
                
            }
        } 
        else{
            JOptionPane.showMessageDialog(null, "OCUPADO: "+ linha + ", " + coluna);
        }        
    }    
    private JButton jogadaComputador(String cmp){
        if (cmp != null) {
            JButton lista[] = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9};          
            for (int i=0;i<lista.length;i++){
                 if (cmp.equals(lista[i].getName())){
                    return lista[i];
                }
            } 
            return(null);
        }  
        else{
            return(null);
        } 
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoVelhaGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel NumeroDeEmpates;
    private javax.swing.JLabel NumeroDevitoriaDoJogador1;
    private javax.swing.JLabel NumerosDeVitoriasDoJogador2;
    private javax.swing.JButton btBinario;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btMatriz;
    private javax.swing.JButton btMatrizInversa;
    private javax.swing.JButton btMatrizTransposta;
    private javax.swing.JButton btMultiMatriz;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSomaMatriz;
    private javax.swing.JButton btSubMatriz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem jmnIniciar;
    private javax.swing.JMenu jmnJogo;
    private javax.swing.JMenuItem jmnJogoVelha;
    private javax.swing.JMenuItem jmnMostrarRanking;
    private javax.swing.JRadioButtonMenuItem jmnPC;
    private javax.swing.JRadioButtonMenuItem jmnPP;
    private javax.swing.JMenu jmnRanking;
    private javax.swing.JMenuItem jmnSair;
    private javax.swing.JMenu jmnSobre;
    private javax.swing.JMenu jmnTipo;
    private javax.swing.JMenuItem jmnZerarRanking;
    private javax.swing.JLabel lbJogo;
    private javax.swing.ButtonGroup mnGrupo;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnJogadas;
    // End of variables declaration//GEN-END:variables
}
